### ISSUE TITLE
Create rtdp CLI command

### ISSUE THREAD

**Issue by faustus123** [JeffersonLab/SRO-RTDP#16]
Create an `rtdp` command line tool that can be used to launch an RTDP session.

This should probably be written in Python (v3)

This does not need full functionality, but should have the basic command parsing with these options:

- running `rtdp` with no arguments prints usage statement
- running `rtdp -h` or `rtdp --help` prints more detailed help. This can include a URL to the Github site.
- running `rtdp --version` prints the current version.
- running `rtdp configFile.yaml` starts the platform using the specified YAML configuration file

New command line arguments will be added as the project develops so the code structure should anticipate that. 
Limit dependencies by using only standard packages. 

Place in an appropriate directory in the GitHub repository and add a markdown file to describe what it is.

**Comment by cissieAB** [comment]
Some useful resource:
- [sfapi_client](https://nersc.github.io/sfapi_client/): SuperFacilityAPI's Python client.
- swif2
