### ISSUE TITLE
Superfacility Scheduler Simulation

### ISSUE THREAD

**Issue by faustus123** [JeffersonLab/SRO-RTDP#18]
The NERSC Superfacility documentation mentions a Scheduling Simulator. Investigate how to run this and how it may be coupled to an RTDP simulation.

This issue will be completed by additional issues being added that detail the work needed to integrate their simulator as an optional component in and RTDP configuration.

**Comment by cissieAB** [comment]
Something might be related: https://github.com/ramsesproject/superfacility

**Comment by cissieAB** [comment]
I do not think we need this anymore
