### ISSUE TITLE
Explore auto documentation generation from Python doc strings with Sphinx

### ISSUE THREAD

**Issue by cissieAB** [JeffersonLab/SRO-RTDP#22]
I followed the tutorial at [Sphinx - How to generate documentation from python doc strings - Five + Minutes on Tips and Tricks](https://www.youtube.com/watch?v=BWIrhgCAae0) and already succeeded with current repo structure.

One step further, this process can be automated with CI once we have configured the doc/code structure well.

**Comment by cissieAB** [comment]
I am reopening this issue to see
- [ ] If it still works well after more and more scripts are added.
- [ ] Does it support auto doc generation for other languages, such as Java/C++, or, is there any other tools for other languages.
- [ ] How to include *.md into the document structure.

**Comment by faustus123** [comment]
Closing this completed. The R&D done demonstrated this is possible. At this point though, the directory structure of RTDP is not coherent enough to make this a useful exercise. A new issue will be opened later once the repository is cleaned up.
