### ISSUE TITLE
Add CMakeLists.txt to SRO-RTDP

### ISSUE THREAD

**Issue by faustus123** [JeffersonLab/SRO-RTDP#24]
Add a CMakeLists.txt file to the top level of the SRO-RTDP directory. This should be done after PR #21 is merged so it can install the `rtdp.py` script as `rtdp` into an installation bin directory.

This will eventually need to create other directories for python modules, C/C++ libraries, plugins, Java classes, etc. These may not need to be added just now, but keep it in mind when structuring the cmake configuration.

**Comment by AyanRoy16** [comment]
Added the Cmake for the python file. Feel free to re open when needed
