### ISSUE TITLE
ERSAP Actor Config. Parameter Retrieval

### ISSUE THREAD

**Issue by faustus123** [JeffersonLab/SRO-RTDP#26]
Understand how to retrieve configuration parameters for a specific actor from an ERSAP configuration.

Put example actors in the repository in directories:

`rtdp/cpp/examples`
`rtdp/java/examples`

**Comment by AyanRoy16** [comment]
Update: The examples in the branch ([https://github.com/JeffersonLab/ersap-actor/tree/Ayan16_ERSAP_Intro]) is retrieving the configuration parameters (file location and port number) inside the specific actors.
