### ISSUE TITLE
Create Hello World ERSAP Configuration

### ISSUE THREAD

**Issue by faustus123** [JeffersonLab/SRO-RTDP#4]
Find an example ERSAP configuration and create our own Hello World example that includes 3 components for reading from a file and processing the data with a CPU simulation actor. (The CPU simulator actor will be written as part of another issue.)

**Comment by AyanRoy16** [comment]
This is done. Corresponding Branch: https://github.com/JeffersonLab/ersap-actor/tree/Ayan16_ERSAP_Intro.

**Comment by AyanRoy16** [comment]
As of now I am closing the issue. Feel free to reopen it
