### ISSUE TITLE
Establish Prometheus server and test

### ISSUE THREAD

**Issue by faustus123** [JeffersonLab/SRO-RTDP#49]
- [x] Identify server(s) where existing prometheus DBs are running at JLab
- [x] Determine an appropriate configuration for a prometheus server to be used for monitoring large scale RTDP simulations
  - This should be able to access any JLab node in the DAQ network (e.g. clonfarm21) as well as any SciComp farm node
- [x] <s>Submit a SN request to have an RTDP DB stood up with appropriate permissions
  - If no more appropriate server is found, have it installed on epscidb.jlab.org</s> (*Removed since it's not required anymore*)
- [x] Test DB using Docker node exporter or podman equivalent
  - This can be as simple as running iperf3 as server/client on two farm worker nodes using [interactive sessions](https://scicomp.jlab.org/docs/farm_slurm_batch_interactive_jobs) (don't use ifarm for this)

**Comment by cissieAB** [comment]
Something related to the first item:
@faustus123 
For existing (by Bryan's team) ifarm monitoring, there is a public Grafana dashboard at https://scigraf.jlab.org/. Use the JLab CUE usr/psd to login, then you are available to see the Prometheus metrics of all ifarm nodes. It's based on the node-exporter for Promtheus.
![image](https://github.com/user-attachments/assets/efc7bef8-c992-4797-a6a9-9dcec8473f47)

**Comment by cissieAB** [comment]
The Prometheus DB for ifarm nodes should be on:
$ nslookup sci-prometheus.jlab.org
Server:		129.57.90.255
Address:	129.57.90.255#53

Name:	sci-prometheus.jlab.org
Address: 129.57.16.202

**Comment by faustus123** [comment]
Do have permission to write to that DB for things that are not directly related to SciComp operations?

**Comment by cissieAB** [comment]
> Do have permission to write to that DB for things that are not directly related to SciComp operations?

I do not think we have write permission. I think we do not have read permission either. After some negotiation, Bryan might give you read permission but he should not be happy if we port our own stuff to it.

I will see if I can run a dockerized/podmanrized Prometheus image on one of the ifarm login nodes.

**Comment by cissieAB** [comment]
> > Do have permission to write to that DB for things that are not directly related to SciComp operations?
> 
> I do not think we have write permission. I think we do not have read permission either. After some negotiation, Bryan might give you read permission but he should not be happy if we port our own stuff to it.
> 
> I will see if I can run a dockerized/podmanrized Prometheus image on one of the ifarm login nodes.

We may have read permission:
```bash
[xmei@ifarm2401 ~]$ curl 129.57.16.202:9090
<a href="/prometheus">Found</a>.
```

**Comment by faustus123** [comment]
> _NOTE_: only certain range of TCP ports is allowed on ifarm for inter-compute node communication (no login-compute communication). The port range is typed in Teams chat for security issue.

If this is only for nodes within the SciComp farm proper (i.e. excluding ifarm nodes) then I am confused why it would be considered a security issue. Regardless, if it is not a publicly know thing, they could change it at any point, breaking whatever system we have set up. We should press them for more info or for a suggestion on how we properly can get RPC for monitoring purposes.

**Comment by cissieAB** [comment]
@faustus123 Create a PR for this: https://github.com/JeffersonLab/SRO-RTDP/pull/52

![image](https://github.com/user-attachments/assets/a2de49d9-f002-478c-abb3-c4d7af1e16f4)

**Comment by cissieAB** [comment]
![image](https://github.com/user-attachments/assets/36a26984-f7bf-435f-ac3f-80e8de593082)

@faustus123 created a PR #52 to address this
